### ISSUE TITLE
你这个库涉嫌抄袭别人啊

### ISSUE THREAD

**Issue by Wangyff** [Cricin/Folivora#1]
[https://github.com/JavaNoober/BackgroundLibrary](https://github.com/JavaNoober/BackgroundLibrary)
看了下时间，别人更新了什么，你就更新了什么，变量名有的都没改，代码思路顺序也基本一样。。。。把别人的代码搬过来改个名字顺序。。。有意思吗

**Comment by Cricin** [comment]
首先， 我也注意到了你说的这个库，在我写0.0.4版本的时候，发现原来已经有这样的轮子了。不得不说就像被浇了一盆凉水一样，但是看了一下这个库的代码，和folivora还是有些差别的，至少folivora的功能更多更完善点。这个库和你说的那个库原理都是相同的，都是在LayoutInflater上做文章

说说不同点好吧：bl -> BackgroundLibrary，    f -> Folivora
1. 首先bl的那一套，作者只支持了shape，selector，ripple之类的，并且好多属性都是糅合在一起的，f支持了大多数android自带的drawable，每一个drawable用到的属性都是分开的。
2. f支持自定义的drawable，包括drawable的自定义属性和属性自动提示，bl是不支持的。
3. f提供了内嵌shape的功能，任意容器drawable都可以内嵌shape，比如说实现一个圆角点击变色的selector，f只需要用两个圆角shape嵌在selector中就可以了，属性都是分开的，bl的做法是直接把selector和shape糅合在一起了，比如bl_pressed_stroke_color, 有selector相关的又有shape相关的。
4. bl提供在运行时方便开发者生成drawable使用的drawabe creator, f没有提供，也不会提供，f只关注从layout文件中绑定drawable，我认为，大多数的项目中都会有一套自己封装的快捷创建drawable的工具类。这部分没有必要，我一开始就没有考虑做。
5. f的lint相关代码是为了集成xml代码提示引入的，实现lint这部分代码资料都很少，网上的教程也有，但是大部分都是过时的，很多api都更新了，这部分我摸索了好几天。

在0.0.4版本中加入的插桩view来支持预览的功能，这方面我确实是借鉴了bl的做法，这样更简单，兼容性也更好，但是这个不是f和bl的主要功能，都是为了使用者有更好的使用体验，用不用都不影响正常功能，应该不算核心代码吧。f在之前几个版本中，这部分功能，都是单独的支持工具做的，具体就是hook Android Studio，代码在/preview_support下还能找到，这部分内容，说实话，让你hook Android Studio的预览窗口，真的是两眼一抹黑，硬看[Android插件的源码](https://github.com/JetBrains/android)，主要还是兼容问题太多，最后我也改成了插桩view的方式。(f在0.0.1版本就支持预览了，我看了一下bl的提交记录，这时候的bl还不支持)

xml代码提示部分，bl使用的是Live Templates，f从一开始就是hook Android Studio来做的，具体实现代码可以在/lint下找到，这也就是说，f的代码提示更加准确，是跟随Studio来的,也不需要你下载什么xml文件放到哪里哪里。你想想,按bl那一套Live Templates搞，想支持自定义drawable的属性提示跟本是不可能的，或者哪怕只更新一个自定义的属性，你都得更新一下bl的xml配置文件才能使用新属性自动提示，f完全不需要。

你说的抄袭是在哪里？获取自定义属性吗？ 这种代码都是模板代码啊，你编写自定义view不也是这样获取的吗？FolivoraViewFactory吗？只要是做LayoutInflater.FactoryXX相关的，创建view的代码都是大同小异的吧，看[Android-skin-support](https://github.com/ximsfei/Android-skin-support/blob/master/android/skin/src/main/java/skin/support/app/SkinCompatViewInflater.java)和[Calligraphy](https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyLayoutInflater.java), 人家Skin-Support和Calligraphy也是这样写的啊, 代码和f的也很相似啊，各种各样的换肤框架也有好多这种相似的地方。多数都是抄的原生LayoutInflater的代码。

总结一下:  做Folivora的思路，源于[Calligraphy](https://github.com/chrisjenx/Calligraphy/)和[ViewPump](https://github.com/InflationX/ViewPump)，0.0.4版本的插桩View是用的来自bl的思路。
问题是大多数的项目都有许多自定义view，比如你引入了上面的Android-skin-support，xml代码里面用的大多是框架提供的自定义view，为了支持预览，每个view都要插桩，还是很麻烦的，所以在接下来的版本里，插桩view都会废弃掉，直接原生支持自定义view的预览。

还有什么问题吗？欢迎交流
