### ISSUE TITLE
android studio 无法预览

### ISSUE THREAD

**Issue by jiyuren** [Cricin/Folivora#3]
android studio 无法预览 https://link.juejin.im/?target=https%3A%2F%2Fraw.githubusercontent.com%2FCricin%2FFolivora%2Fmaster%2Fandroid-folivora-support.jar 这个jar 包是该项目中 flivora 库编译出来的吗

**Comment by Cricin** [comment]
新版的Folivora不需要添加这个jar包了，依赖了之后build一下项目应该可以直接预览的

**Comment by jiyuren** [comment]
但是我这预览还是不行的啊，啥情况呢Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by Cricin** [comment]
加我QQ 1278486605

**Comment by jiyuren** [comment]
已解决
