### ISSUE TITLE
AS3.3,gradle3.3,无法预览

### ISSUE THREAD

**Issue by yangqqq537** [Cricin/Folivora#6]
我看到你修复了,但是我这边还是无法预览...运行后效果是有,就是预览没效果很头大..

**Comment by yangqqq537** [comment]
跑了你的项目,一开始可以预览,我就把issue关了,然后关掉项目再进去就怎么都出不来了

**Comment by Cricin** [comment]
是有这样的问题，会偶然出现不能预览的情况，应该是和as的缓存有关，具体原因还没有找到。
