### ISSUE TITLE
Gradient 只设置starColor和EndColor中间有空白

### ISSUE THREAD

**Issue by simplepeng** [Cricin/Folivora#7]
![image](https://user-images.githubusercontent.com/12198830/59013654-16fcf480-886d-11e9-9b19-99023e1c740a.png)
![image](https://user-images.githubusercontent.com/12198830/59013669-254b1080-886d-11e9-9360-68df887ac458.png)
xml哪里写的有问题吗？

**Comment by simplepeng** [comment]
要实现的效果
![image](https://user-images.githubusercontent.com/12198830/59013709-427fdf00-886d-11e9-982b-becea2b0c77a.png)

**Comment by Cricin** [comment]
这好像是Folivora的一个bug，没有判断是否有centerColor导致的，很抱歉，下个版本我会修复这个问题

**Comment by Cricin** [comment]
新版本修复了，依赖0.0.9就可以了
